// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/blog/index.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/ContactButton.tsx";
import * as $$1 from "./islands/ExperienceBoard.tsx";
import * as $$2 from "./islands/FooterNavigation.tsx";
import * as $$3 from "./islands/RepoCard.tsx";
import * as $$4 from "./islands/SkillSection.tsx";

const manifest = {
  routes: {
    "./routes/blog/index.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/ContactButton.tsx": $$0,
    "./islands/ExperienceBoard.tsx": $$1,
    "./islands/FooterNavigation.tsx": $$2,
    "./islands/RepoCard.tsx": $$3,
    "./islands/SkillSection.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
